language: python
python:
    - "2.7"
sudo: false

env:
    - PLATFORMIO_CI_SRC=ardudave

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci --board=leonardo
