#include <avr/pgmspace.h>

#define TONE(len, freq) ( ((len == 1 ? 0 : (len == 2 ? 1 : (len == 4 ? 2 : (len == 8 ? 3 : (len == 16 ? 4 : 0))))) << 13) + freq )
#define TONE_LEN(tone) pow(2, (tone >> 13))
#define TONE_FREQ(tone) ( tone << 3 >> 3 )

// Skakal pes
const static unsigned int melody1[] PROGMEM = {
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, 0),

  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, 0),

  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),

  TONE(4, NOTE_G3),
  TONE(4, NOTE_F3),

  TONE(8, NOTE_F3),
  TONE(8, NOTE_F3),
  TONE(8, NOTE_D3),
  TONE(8, 0),

  TONE(8, NOTE_F3),
  TONE(8, NOTE_F3),
  TONE(8, NOTE_D3),
  TONE(8, 0),

  TONE(8, NOTE_F3),
  TONE(8, NOTE_F3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_F3),

  TONE(4, NOTE_F3),
  TONE(4, NOTE_E3),
};

// Ja do lesa nepojedu
const static unsigned int melody2[] PROGMEM = {
  TONE(8, NOTE_C3),
  TONE(8, NOTE_E3),
  TONE(4, NOTE_G3),
  TONE(4, NOTE_G3),
  TONE(8, NOTE_C4),
  TONE(8, NOTE_C4),
  TONE(4, NOTE_G3),
  TONE(4, NOTE_G3),
  TONE(8, NOTE_F3),
  TONE(8, NOTE_F3),
  TONE(4, NOTE_D3),
  TONE(4, NOTE_D3),
  TONE(8, NOTE_C3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(8, 0),
  TONE(4, 0),
  TONE(8, NOTE_C3),
  TONE(8, NOTE_E3),
  TONE(4, NOTE_G3),
  TONE(4, NOTE_G3),
  TONE(8, NOTE_C4),
  TONE(8, NOTE_C4),
  TONE(4, NOTE_G3),
  TONE(4, NOTE_G3),
  TONE(8, NOTE_F3),
  TONE(8, NOTE_F3),
  TONE(4, NOTE_D3),
  TONE(4, NOTE_D3),
  TONE(8, NOTE_C3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_C3),
  TONE(8, 0),
  TONE(4, 0),
};

// Holka modrooka
const static unsigned int melody3[] PROGMEM = {
  TONE(4, NOTE_FS3),
  TONE(4, NOTE_B3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, 0),
  TONE(4, NOTE_FS3),
  TONE(4, NOTE_B3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(4, NOTE_FS3),
  TONE(4, 0),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, 0),
  TONE(4, NOTE_FS3),
  TONE(4, NOTE_B3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(4, NOTE_FS3),
  TONE(4, 0),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, 0),
  TONE(4, NOTE_FS3),
  TONE(4, NOTE_B3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_A3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_G3),
  TONE(4, NOTE_FS3),
};

// Ja mam kone
const static unsigned int melody4[] PROGMEM = {
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_D3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_D3),

  TONE(8, NOTE_E3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_FS3),
  TONE(2, NOTE_G3),

  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_D3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_D3),

  TONE(8, NOTE_E3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_FS3),
  TONE(2, NOTE_G3),

  TONE(8, NOTE_G3),
  TONE(8, NOTE_B3),
  TONE(8, NOTE_B3),
  TONE(8, NOTE_D4),
  TONE(8, NOTE_D4),
  TONE(8, NOTE_C4),
  TONE(4, NOTE_A3),

  TONE(8, NOTE_G3),
  TONE(8, NOTE_B3),
  TONE(8, NOTE_B3),
  TONE(8, NOTE_D4),
  TONE(8, NOTE_D4),
  TONE(8, NOTE_C4),
  TONE(4, NOTE_A3),

  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_D3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_G3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_D3),

  TONE(8, NOTE_E3),
  TONE(8, NOTE_E3),
  TONE(8, NOTE_FS3),
  TONE(8, NOTE_FS3),
  TONE(2, NOTE_G3),
};

